VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "CPublicEnums"
Attribute VB_GlobalNameSpace = True
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Public Enum OLEDropModeConstants
OLEDropModeNone = vbOLEDropNone
OLEDropModeManual = vbOLEDropManual
End Enum
Public Enum CCAppearanceConstants
CCAppearanceFlat = 0
CCAppearance3D = 1
End Enum
Public Enum CCBorderStyleConstants
CCBorderStyleNone = 0
CCBorderStyleSingle = 1
CCBorderStyleThin = 2
CCBorderStyleSunken = 3
CCBorderStyleRaised = 4
End Enum
Public Enum CCBackStyleConstants
CCBackStyleTransparent = 0
CCBackStyleOpaque = 1
End Enum
Public Enum CCLeftRightAlignmentConstants
CCLeftRightAlignmentLeft = 0
CCLeftRightAlignmentRight = 1
End Enum
Public Enum CCVerticalAlignmentConstants
CCVerticalAlignmentTop = 0
CCVerticalAlignmentCenter = 1
CCVerticalAlignmentBottom = 2
End Enum
Public Enum CCIMEModeConstants
CCIMEModeNoControl = 0
CCIMEModeOn = 1
CCIMEModeOff = 2
CCIMEModeDisable = 3
CCIMEModeHiragana = 4
CCIMEModeKatakana = 5
CCIMEModeKatakanaHalf = 6
CCIMEModeAlphaFull = 7
CCIMEModeAlpha = 8
CCIMEModeHangulFull = 9
CCIMEModeHangul = 10
End Enum

Public Enum LvwViewConstants
LvwViewIcon = 0
LvwViewSmallIcon = 1
LvwViewList = 2
LvwViewReport = 3
LvwViewTile = 4
End Enum
Public Enum LvwArrangeConstants
LvwArrangeNone = 0
LvwArrangeAutoLeft = 1
LvwArrangeAutoTop = 2
LvwArrangeLeft = 3
LvwArrangeTop = 4
End Enum
Public Enum LvwColumnHeaderAlignmentConstants
LvwColumnHeaderAlignmentLeft = 0
LvwColumnHeaderAlignmentRight = 1
LvwColumnHeaderAlignmentCenter = 2
End Enum
Public Enum LvwColumnHeaderSortArrowConstants
LvwColumnHeaderSortArrowNone = 0
LvwColumnHeaderSortArrowDown = 1
LvwColumnHeaderSortArrowUp = 2
End Enum
Public Enum LvwColumnHeaderAutoSizeConstants
LvwColumnHeaderAutoSizeToItems = 0
LvwColumnHeaderAutoSizeToHeader = 1
End Enum
Public Enum LvwColumnHeaderFilterTypeConstants
LvwColumnHeaderFilterTypeText = 0
LvwColumnHeaderFilterTypeNumber = 1
End Enum
Public Enum LvwLabelEditConstants
LvwLabelEditAutomatic = 0
LvwLabelEditManual = 1
LvwLabelEditDisabled = 2
End Enum
Public Enum LvwSortOrderConstants
LvwSortOrderAscending = 0
LvwSortOrderDescending = 1
End Enum
Public Enum LvwSortTypeConstants
LvwSortTypeBinary = 0
LvwSortTypeText = 1
LvwSortTypeNumeric = 2
LvwSortTypeCurrency = 3
LvwSortTypeDate = 4
End Enum
Public Enum LvwPictureAlignmentConstants
LvwPictureAlignmentTopLeft = 0
LvwPictureAlignmentTopRight = 1
LvwPictureAlignmentBottomLeft = 2
LvwPictureAlignmentBottomRight = 3
LvwPictureAlignmentCenter = 4
LvwPictureAlignmentTile = 5
End Enum
Public Enum LvwGroupHeaderAlignmentConstants
LvwGroupHeaderAlignmentLeft = 0
LvwGroupHeaderAlignmentRight = 1
LvwGroupHeaderAlignmentCenter = 2
End Enum
Public Enum LvwGroupFooterAlignmentConstants
LvwGroupFooterAlignmentLeft = 0
LvwGroupFooterAlignmentRight = 1
LvwGroupFooterAlignmentCenter = 2
End Enum

